<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6a100f10616e3',
	'title' => 'Category Settings',
	'fields' => array(
		array(
			'key' => 'field_6a20ae7d646b6',
			'label' => 'Solution',
			'name' => 'related_solution',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'solutions',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a0dbbc36e898',
	'title' => 'Post Settings',
	'fields' => array(
		array(
			'key' => 'field_6a0dbbc315f2f',
			'label' => 'Breadcrumb Title',
			'name' => 'breadcrumb_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Optional. Shortens the post title in breadcrumbs. Leave blank to use the full post title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a0fda65d215a',
			'label' => 'CTA Button',
			'name' => 'cta_button',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_6a105ef5e1b71',
			'label' => 'Author',
			'name' => 'post_author_ref',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'authors',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6a17d4fd884cd',
			'label' => 'Hero Image',
			'name' => 'hero_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Leave empty to use the featured image in the header.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'press-article',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a1e022de5da6',
	'title' => 'Solution Settings',
	'fields' => array(
		array(
			'key' => 'field_6a225b0ed6b08',
			'label' => 'Breadcrumb Title',
			'name' => 'breadcrumb_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Optional. Shortens the post title in breadcrumbs. Leave blank to use the full post title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a1e0271ae913',
			'label' => 'Accent Color',
			'name' => 'accent_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_6a1e02ccae914',
			'label' => 'Icon',
			'name' => 'solution_icon',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'' => '— None —',
				'aptify' => 'Aptify',
				'article' => 'Article',
				'book-content' => 'Book Content',
				'briefcase' => 'Briefcase',
				'bx-analyse' => 'Bx Analyse',
				'bx-award' => 'Bx Award',
				'bx-badge-check' => 'Bx Badge Check',
				'bx-bar-chart-alt' => 'Bx Bar Chart Alt',
				'bx-bar-chart-alt-2' => 'Bx Bar Chart Alt 2',
				'bx-bar-chart-square' => 'Bx Bar Chart Square',
				'bx-barcode-reader' => 'Bx Barcode Reader',
				'bx-bolt-circle' => 'Bx Bolt Circle',
				'bx-book-bookmark' => 'Bx Book Bookmark',
				'bx-book-content' => 'Bx Book Content',
				'bx-book-heart' => 'Bx Book Heart',
				'bx-briefcase' => 'Bx Briefcase',
				'bx-briefcase-alt-2' => 'Bx Briefcase Alt 2',
				'bx-bulb' => 'Bx Bulb',
				'bx-bullseye' => 'Bx Bullseye',
				'bx-calculator' => 'Bx Calculator',
				'bx-calendar' => 'Bx Calendar',
				'bx-calendar-check' => 'Bx Calendar Check',
				'bx-calendar-edit' => 'Bx Calendar Edit',
				'bx-calendar-event' => 'Bx Calendar Event',
				'bx-calendar-star' => 'Bx Calendar Star',
				'bx-camera-movie' => 'Bx Camera Movie',
				'bx-cart-alt' => 'Bx Cart Alt',
				'bx-category' => 'Bx Category',
				'bx-category-alt' => 'Bx Category Alt',
				'bx-certification' => 'Bx Certification',
				'bx-chalkboard' => 'Bx Chalkboard',
				'bx-chart' => 'Bx Chart',
				'bx-check' => 'Bx Check',
				'bx-check-circle' => 'Bx Check Circle',
				'bx-check-double' => 'Bx Check Double',
				'bx-check-shield' => 'Bx Check Shield',
				'bx-check-square' => 'Bx Check Square',
				'bx-cog' => 'Bx Cog',
				'bx-columns' => 'Bx Columns',
				'bx-comment-check' => 'Bx Comment Check',
				'bx-comment-detail' => 'Bx Comment Detail',
				'bx-conversation' => 'Bx Conversation',
				'bx-copy-alt' => 'Bx Copy Alt',
				'bx-credit-card-front' => 'Bx Credit Card Front',
				'bx-customize' => 'Bx Customize',
				'bx-data' => 'Bx Data',
				'bx-desktop' => 'Bx Desktop',
				'bx-detail' => 'Bx Detail',
				'bx-diamond' => 'Bx Diamond',
				'bx-dollar' => 'Bx Dollar',
				'bx-dollar-circle' => 'Bx Dollar Circle',
				'bx-donate-heart' => 'Bx Donate Heart',
				'bx-edit-alt' => 'Bx Edit Alt',
				'bx-error-circle' => 'Bx Error Circle',
				'bx-extension' => 'Bx Extension',
				'bx-file' => 'Bx File',
				'bx-file-find' => 'Bx File Find',
				'bx-filter-alt' => 'Bx Filter Alt',
				'bx-gift' => 'Bx Gift',
				'bx-git-branch' => 'Bx Git Branch',
				'bx-git-compare' => 'Bx Git Compare',
				'bx-git-merge' => 'Bx Git Merge',
				'bx-git-repo-forked' => 'Bx Git Repo Forked',
				'bx-globe' => 'Bx Globe',
				'bx-grid-alt' => 'Bx Grid Alt',
				'bx-group' => 'Bx Group',
				'bx-happy' => 'Bx Happy',
				'bx-happy-alt' => 'Bx Happy Alt',
				'bx-heart' => 'Bx Heart',
				'bx-heart-circle' => 'Bx Heart Circle',
				'bx-hourglass' => 'Bx Hourglass',
				'bx-id-card' => 'Bx Id Card',
				'bx-info-circle' => 'Bx Info Circle',
				'bx-like' => 'Bx Like',
				'bx-line-chart' => 'Bx Line Chart',
				'bx-list-check' => 'Bx List Check',
				'bx-list-plus' => 'Bx List Plus',
				'bx-lock' => 'Bx Lock',
				'bx-message-detail' => 'Bx Message Detail',
				'bx-minus' => 'Bx Minus',
				'bx-mobile' => 'Bx Mobile',
				'bx-mobile-alt' => 'Bx Mobile Alt',
				'bx-money' => 'Bx Money',
				'bx-movie-play' => 'Bx Movie Play',
				'bx-network-chart' => 'Bx Network Chart',
				'bx-notification' => 'Bx Notification',
				'bx-package' => 'Bx Package',
				'bx-paper-plane' => 'Bx Paper Plane',
				'bx-pencil' => 'Bx Pencil',
				'bx-pie-chart-alt-2' => 'Bx Pie Chart Alt 2',
				'bx-play-circle' => 'Bx Play Circle',
				'bx-plus' => 'Bx Plus',
				'bx-pointer' => 'Bx Pointer',
				'bx-refresh' => 'Bx Refresh',
				'bx-rename' => 'Bx Rename',
				'bx-restaurant' => 'Bx Restaurant',
				'bx-rocket' => 'Bx Rocket',
				'bx-shape-circle' => 'Bx Shape Circle',
				'bx-shape-polygon' => 'Bx Shape Polygon',
				'bx-shield-quarter' => 'Bx Shield Quarter',
				'bx-shopping-bag' => 'Bx Shopping Bag',
				'bx-sitemap' => 'Bx Sitemap',
				'bx-slider' => 'Bx Slider',
				'bx-slider-alt' => 'Bx Slider Alt',
				'bx-star' => 'Bx Star',
				'bx-support' => 'Bx Support',
				'bx-tachometer' => 'Bx Tachometer',
				'bx-time' => 'Bx Time',
				'bx-trending-up' => 'Bx Trending Up',
				'bx-trip' => 'Bx Trip',
				'bx-trophy' => 'Bx Trophy',
				'bx-user-check' => 'Bx User Check',
				'bx-user-circle' => 'Bx User Circle',
				'bx-user-plus' => 'Bx User Plus',
				'bx-video-recording' => 'Bx Video Recording',
				'bx-window-alt' => 'Bx Window Alt',
				'bx-wrench' => 'Bx Wrench',
				'bx-x' => 'Bx X',
				'calculator' => 'Calculator',
				'calendar' => 'Calendar',
				'certificate' => 'Certificate',
				'cobalt' => 'Cobalt',
				'dollar-sign' => 'Dollar Sign',
				'donation' => 'Donation',
				'file-detail' => 'File Detail',
				'grad' => 'Grad',
				'headphones' => 'Headphones',
				'heart-with-clasped-hands' => 'Heart With Clasped Hands',
				'iq' => 'Iq',
				'iq-alt' => 'Iq Alt',
				'loader-dots' => 'Loader Dots',
				'message-detail' => 'Message Detail',
				'molecule' => 'Molecule',
				'momentive-iq' => 'Momentive Iq',
				'movie-play' => 'Movie Play',
				'netforum' => 'Netforum',
				'nimble' => 'Nimble',
				'path' => 'Path',
				'people' => 'People',
				'rocket' => 'Rocket',
				'yourmembership' => 'Yourmembership',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6a1e02ffae915',
			'label' => 'Background Image',
			'name' => 'background_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
		array(
			'key' => 'field_6a20b62df882b',
			'label' => 'Label for Solution Card',
			'name' => 'card_label',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'This text will appear on the top right of the card when the solution is shown in the light card design.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'solutions',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a23a12ae0f19',
	'title' => 'Testimonial Settings',
	'fields' => array(
		array(
			'key'          => 'field_testimonial_solution',
			'label'        => 'Solution Family',
			'name'         => 'testimonial_solution',
			'type'         => 'taxonomy',
			'taxonomy'     => 'category',
			'field_type'   => 'select',
			'multiple'     => 0,
			'allow_null'   => 1,
			'save_terms'   => 1,          // actually assigns the category to the post
			'load_terms'   => 1,          // pre-selects based on current assignment
			'return_format' => 'id',
		),
		array(
			'key' => 'field_6a23a12b985dc',
			'label' => 'Author Name',
			'name' => 'testimonial_author_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a23a163985dd',
			'label' => 'Author Description',
			'name' => 'testimonial_author_description',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a23a17d985de',
			'label' => 'Author Photo',
			'name' => 'testimonial_author_photo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6a23a1a0985df',
			'label' => 'Testimonial Type',
			'name' => 'testimonial_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'client' => 'Client',
				'partner' => 'Partner',
				'other' => 'Other',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6a23a1d7985e0',
			'label' => 'Related Case Study',
			'name' => 'related_case_study',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'testimonials',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );
} );

