<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6a421df4548b3',
	'title' => 'Case Study Settings',
	'fields' => array(
		array(
			'key' => 'field_6a421dd3f32a8',
			'label' => 'Breadcrumb Title',
			'name' => 'breadcrumb_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Optional. Shortens the post title in breadcrumbs. Leave blank to use the full post title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a429f79316b5',
			'label' => 'Products',
			'name' => 'linked_products',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Select the products to display. Logos and links are pulled from each product automatically.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'product',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 1,
			'allow_null' => 1,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'case-study',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a100f10616e3',
	'title' => 'Category Settings',
	'fields' => array(
		array(
			'key' => 'field_6a20ae7d646b6',
			'label' => 'Solution',
			'name' => 'related_solution',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'solutions',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a2f336a848ad',
	'title' => 'FAQ Settings',
	'fields' => array(
		array(
			'key' => 'field_6a2f336b53521',
			'label' => 'Solution Family',
			'name' => 'faq_solution',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'faq',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a2873b9cd824',
	'title' => 'HubSpot Form',
	'fields' => array(
		array(
			'key' => 'field_6a2873ba3bf87',
			'label' => 'Embed Code',
			'name' => 'hubspot_embed_code',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Paste the HubSpot embed snippet here to override the post-level form. Leave blank to use the webinar\'s form_upcoming / form_ondemand field automatically.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a35626f3a11b',
			'label' => 'Two-Step Email Capture',
			'name' => 'two_step',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/hubspot-form',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a429f79214af',
	'title' => 'Linked Products Block Settings',
	'fields' => array(
		array(
			'key' => 'field_6a429fb9316b6',
			'label' => 'Heading',
			'name' => 'heading',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Heading shown above the list. Defaults to "Solutions"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Solutions',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a42a00e316b7',
			'label' => 'Show Heading',
			'name' => 'show_heading',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_6a42aac112ead',
			'label' => 'Products',
			'name' => 'linked_products',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Select the products to display. If the post has linked products, leave this blank to inherit them.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'product',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 1,
			'allow_null' => 1,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'momentive/linked-products',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a404096e0e64',
	'title' => 'Person Block Settings',
	'fields' => array(
		array(
			'key' => 'field_6a4040979a5a0',
			'label' => 'Person',
			'name' => 'person',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'people',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/person',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a3eabe56be4a',
	'title' => 'Person Settings',
	'fields' => array(
		array(
			'key' => 'field_6a3eac6676c0e',
			'label' => 'First Name',
			'name' => 'first_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a3eac6d76c0f',
			'label' => 'Last Name',
			'name' => 'last_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a3eabe576c0c',
			'label' => 'Position',
			'name' => 'job_position',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a3eac0076c0d',
			'label' => 'LinkedIn Profile',
			'name' => 'linkedin_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'people',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a0dbbc36e898',
	'title' => 'Post Settings',
	'fields' => array(
		array(
			'key' => 'field_6a0dbbc315f2f',
			'label' => 'Breadcrumb Title',
			'name' => 'breadcrumb_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Optional. Shortens the post title in breadcrumbs. Leave blank to use the full post title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a0fda65d215a',
			'label' => 'CTA Button',
			'name' => 'cta_button',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_6a105ef5e1b71',
			'label' => 'Author',
			'name' => 'post_author_ref',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Defaults to your linked profile; change it if you\'re posting on behalf of someone else',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'people',
			),
			'post_status' => '',
			'taxonomy' => array(
				0 => 'person_role:author',
			),
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6a17d4fd884cd',
			'label' => 'Hero Image',
			'name' => 'hero_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Leave empty to use the featured image in the header.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'press-article',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a315103ceeae',
	'title' => 'Product Settings',
	'fields' => array(
		array(
			'key' => 'field_6a3217e7f7911',
			'label' => 'Basics',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6a32e41fcff4c',
			'label' => 'Summary',
			'name' => 'product_summary',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'This summary appears on cards like the ones shown on the main Products archive.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => 'product-summary',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_6a31522708095',
			'label' => 'Solution Family',
			'name' => 'product_category',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6a315103d240e',
			'label' => 'Breadcrumb Title',
			'name' => 'breadcrumb_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Optional. Shortens the post title in breadcrumbs. Leave blank to use the full post title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a371ffc1c6c6',
			'label' => 'Page Accent Color',
			'name' => 'page_accent_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Use this field to set a custom accent color for the product page. If not entered, the product page will use the site\'s default accent color.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_6a32e412cff4b',
			'label' => 'Order',
			'name' => 'product_order',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'This controls where the product appears in product lists.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a32179ef7910',
			'label' => 'Logos',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6a32163fecf51',
			'label' => 'Product Logo (Unendorsed)',
			'name' => 'product_logo_unendorsed',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
		array(
			'key' => 'field_6a32169eecf52',
			'label' => 'Product Logo (Endorsed)',
			'name' => 'product_logo_endorsed',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
		array(
			'key' => 'field_6a3216e0ecf54',
			'label' => 'White Product Logo (Unendorsed)',
			'name' => 'white_product_logo_unendorsed',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
		array(
			'key' => 'field_6a3216b8ecf53',
			'label' => 'White Product Logo (Endorsed)',
			'name' => 'white_product_logo_endorsed',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
		array(
			'key' => 'field_6a315103d2416',
			'label' => 'Icon',
			'name' => 'product_icon',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6a315103d2413',
			'label' => 'Icon Color',
			'name' => 'accent_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a3b7203830a1',
	'title' => 'Recording Block Settings',
	'fields' => array(
		array(
			'key' => 'field_6a3b72040796e',
			'label' => 'Source',
			'name' => 'recording_source',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Use "Post field" for webinars and other posts that store their recording in the Recording panel. Use "Block field" to embed a one-off video here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'post' => 'Post field',
				'block' => 'Block field',
			),
			'default_value' => 'post',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6a3b72630796f',
			'label' => 'Video Embed Code',
			'name' => 'block_video_embed_code',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Paste a video embed code (Wistia, Vimeo, or YouTube) to show in this block.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6a3b72040796e',
						'operator' => '!=',
						'value' => 'post',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/recording',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a1e022de5da6',
	'title' => 'Solution Settings',
	'fields' => array(
		array(
			'key' => 'field_6a3ef82fcb0cd',
			'label' => 'Basics',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6a225b0ed6b08',
			'label' => 'Breadcrumb Title',
			'name' => 'breadcrumb_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Optional. Shortens the post title in breadcrumbs. Leave blank to use the full post title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a1e0271ae913',
			'label' => 'Accent Color',
			'name' => 'accent_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_6a1e02ccae914',
			'label' => 'Icon',
			'name' => 'solution_icon',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'' => '— None —',
				'a2z' => 'A2z',
				'aptify' => 'Aptify',
				'article' => 'Article',
				'book-content' => 'Book Content',
				'briefcase' => 'Briefcase',
				'bx-analyse' => 'Bx Analyse',
				'bx-apartment' => 'Bx Apartment',
				'bx-award' => 'Bx Award',
				'bx-badge-check' => 'Bx Badge Check',
				'bx-bank' => 'Bx Bank',
				'bx-bar-chart-alt' => 'Bx Bar Chart Alt',
				'bx-bar-chart-alt-2' => 'Bx Bar Chart Alt 2',
				'bx-bar-chart-square' => 'Bx Bar Chart Square',
				'bx-barcode-reader' => 'Bx Barcode Reader',
				'bx-blanket' => 'Bx Blanket',
				'bx-bolt-circle' => 'Bx Bolt Circle',
				'bx-book-bookmark' => 'Bx Book Bookmark',
				'bx-book-content' => 'Bx Book Content',
				'bx-book-heart' => 'Bx Book Heart',
				'bx-bookmark-star' => 'Bx Bookmark Star',
				'bx-briefcase' => 'Bx Briefcase',
				'bx-briefcase-alt-2' => 'Bx Briefcase Alt 2',
				'bx-building-house' => 'Bx Building House',
				'bx-bulb' => 'Bx Bulb',
				'bx-bullseye' => 'Bx Bullseye',
				'bx-calculator' => 'Bx Calculator',
				'bx-calendar' => 'Bx Calendar',
				'bx-calendar-check' => 'Bx Calendar Check',
				'bx-calendar-edit' => 'Bx Calendar Edit',
				'bx-calendar-event' => 'Bx Calendar Event',
				'bx-calendar-star' => 'Bx Calendar Star',
				'bx-camera-movie' => 'Bx Camera Movie',
				'bx-cart-alt' => 'Bx Cart Alt',
				'bx-category' => 'Bx Category',
				'bx-category-alt' => 'Bx Category Alt',
				'bx-certification' => 'Bx Certification',
				'bx-chalkboard' => 'Bx Chalkboard',
				'bx-chart' => 'Bx Chart',
				'bx-check' => 'Bx Check',
				'bx-check-circle' => 'Bx Check Circle',
				'bx-check-double' => 'Bx Check Double',
				'bx-check-shield' => 'Bx Check Shield',
				'bx-check-square' => 'Bx Check Square',
				'bx-chevron-right' => 'Bx Chevron Right',
				'bx-clock' => 'Bx Clock',
				'bx-cog' => 'Bx Cog',
				'bx-columns' => 'Bx Columns',
				'bx-comment-check' => 'Bx Comment Check',
				'bx-comment-detail' => 'Bx Comment Detail',
				'bx-community' => 'Bx Community',
				'bx-conversation' => 'Bx Conversation',
				'bx-copy-alt' => 'Bx Copy Alt',
				'bx-copy-check' => 'Bx Copy Check',
				'bx-credit-card-front' => 'Bx Credit Card Front',
				'bx-customize' => 'Bx Customize',
				'bx-data' => 'Bx Data',
				'bx-desktop' => 'Bx Desktop',
				'bx-detail' => 'Bx Detail',
				'bx-diamond' => 'Bx Diamond',
				'bx-discount' => 'Bx Discount',
				'bx-dollar' => 'Bx Dollar',
				'bx-dollar-circle' => 'Bx Dollar Circle',
				'bx-donate-heart' => 'Bx Donate Heart',
				'bx-edit-alt' => 'Bx Edit Alt',
				'bx-error-circle' => 'Bx Error Circle',
				'bx-extension' => 'Bx Extension',
				'bx-file' => 'Bx File',
				'bx-file-detail-alt' => 'Bx File Detail Alt',
				'bx-file-find' => 'Bx File Find',
				'bx-filter-alt' => 'Bx Filter Alt',
				'bx-gift' => 'Bx Gift',
				'bx-git-branch' => 'Bx Git Branch',
				'bx-git-compare' => 'Bx Git Compare',
				'bx-git-merge' => 'Bx Git Merge',
				'bx-git-repo-forked' => 'Bx Git Repo Forked',
				'bx-globe' => 'Bx Globe',
				'bx-grid-alt' => 'Bx Grid Alt',
				'bx-group' => 'Bx Group',
				'bx-happy' => 'Bx Happy',
				'bx-happy-alt' => 'Bx Happy Alt',
				'bx-heart' => 'Bx Heart',
				'bx-heart-circle' => 'Bx Heart Circle',
				'bx-hourglass' => 'Bx Hourglass',
				'bx-id-card' => 'Bx Id Card',
				'bx-info-circle' => 'Bx Info Circle',
				'bx-like' => 'Bx Like',
				'bx-line-chart' => 'Bx Line Chart',
				'bx-list-check' => 'Bx List Check',
				'bx-list-plus' => 'Bx List Plus',
				'bx-loader-dots' => 'Bx Loader Dots',
				'bx-lock' => 'Bx Lock',
				'bx-message-circle-question-mark' => 'Bx Message Circle Question Mark',
				'bx-message-detail' => 'Bx Message Detail',
				'bx-minus' => 'Bx Minus',
				'bx-mobile' => 'Bx Mobile',
				'bx-mobile-alt' => 'Bx Mobile Alt',
				'bx-money' => 'Bx Money',
				'bx-movie-play' => 'Bx Movie Play',
				'bx-network-chart' => 'Bx Network Chart',
				'bx-notepad' => 'Bx Notepad',
				'bx-notification' => 'Bx Notification',
				'bx-package' => 'Bx Package',
				'bx-paper-plane' => 'Bx Paper Plane',
				'bx-pencil' => 'Bx Pencil',
				'bx-phone' => 'Bx Phone',
				'bx-pie-chart-alt-2' => 'Bx Pie Chart Alt 2',
				'bx-play-circle' => 'Bx Play Circle',
				'bx-play-circle-alt' => 'Bx Play Circle Alt',
				'bx-plus' => 'Bx Plus',
				'bx-pointer' => 'Bx Pointer',
				'bx-qr' => 'Bx Qr',
				'bx-refresh' => 'Bx Refresh',
				'bx-rename' => 'Bx Rename',
				'bx-restaurant' => 'Bx Restaurant',
				'bx-rocket' => 'Bx Rocket',
				'bx-shape-circle' => 'Bx Shape Circle',
				'bx-shape-polygon' => 'Bx Shape Polygon',
				'bx-shield-quarter' => 'Bx Shield Quarter',
				'bx-shopping-bag' => 'Bx Shopping Bag',
				'bx-sitemap' => 'Bx Sitemap',
				'bx-slider' => 'Bx Slider',
				'bx-slider-alt' => 'Bx Slider Alt',
				'bx-sort-alt-2' => 'Bx Sort Alt 2',
				'bx-star' => 'Bx Star',
				'bx-support' => 'Bx Support',
				'bx-tachometer' => 'Bx Tachometer',
				'bx-time' => 'Bx Time',
				'bx-trending-up' => 'Bx Trending Up',
				'bx-trip' => 'Bx Trip',
				'bx-trophy' => 'Bx Trophy',
				'bx-user' => 'Bx User',
				'bx-user-check' => 'Bx User Check',
				'bx-user-circle' => 'Bx User Circle',
				'bx-user-plus' => 'Bx User Plus',
				'bx-video-recording' => 'Bx Video Recording',
				'bx-window-alt' => 'Bx Window Alt',
				'bx-wrench' => 'Bx Wrench',
				'bx-x' => 'Bx X',
				'bxs-bar-chart-alt-2' => 'Bxs Bar Chart Alt 2',
				'bxs-book-reader' => 'Bxs Book Reader',
				'bxs-calendar-event' => 'Bxs Calendar Event',
				'bxs-user-badge' => 'Bxs User Badge',
				'calculator' => 'Calculator',
				'calendar' => 'Calendar',
				'calendar-days-full' => 'Calendar Days Full',
				'careers' => 'Careers',
				'certificate' => 'Certificate',
				'certificationmanagement' => 'Certificationmanagement',
				'clock-full' => 'Clock Full',
				'cobalt' => 'Cobalt',
				'configio' => 'Configio',
				'crowd-wisdom' => 'Crowd Wisdom',
				'dollar-sign' => 'Dollar Sign',
				'donation' => 'Donation',
				'eventmanagement' => 'Eventmanagement',
				'file-detail' => 'File Detail',
				'givesmart' => 'Givesmart',
				'grad' => 'Grad',
				'headphones' => 'Headphones',
				'heart-with-clasped-hands' => 'Heart With Clasped Hands',
				'iq' => 'Iq',
				'iq-alt' => 'Iq Alt',
				'linkedin' => 'Linkedin',
				'loader-dots' => 'Loader Dots',
				'message-detail' => 'Message Detail',
				'mip' => 'Mip',
				'molecule' => 'Molecule',
				'momentive-iq' => 'Momentive Iq',
				'movie-play' => 'Movie Play',
				'netforum' => 'Netforum',
				'nimble' => 'Nimble',
				'nucleus' => 'Nucleus',
				'path' => 'Path',
				'people' => 'People',
				'rocket' => 'Rocket',
				'threesixty' => 'Threesixty',
				'volunteermatters' => 'Volunteermatters',
				'wildapricot' => 'Wildapricot',
				'ymc' => 'Ymc',
				'ymc-network' => 'Ymc Network',
				'yourmembership' => 'Yourmembership',
				'youtube' => 'Youtube',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6a32e3f929c42',
			'label' => 'Order',
			'name' => 'solution_order',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a3ef7f1cb0cc',
			'label' => 'Solution Slider Card',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6a1e02ffae915',
			'label' => 'Background Image',
			'name' => 'background_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
		array(
			'key' => 'field_6a20b62df882b',
			'label' => 'Label for Solution Card',
			'name' => 'card_label',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Optional. This text will appear on the top right of the card when the solution is shown in the light card design.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'solutions',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a23a12ae0f19',
	'title' => 'Testimonial Settings',
	'fields' => array(
		array(
			'key' => 'field_6a23a12b985dc',
			'label' => 'Author Name',
			'name' => 'testimonial_author_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a23a163985dd',
			'label' => 'Author Description',
			'name' => 'testimonial_author_description',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a23a17d985de',
			'label' => 'Author Photo',
			'name' => 'testimonial_author_photo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6a23a1a0985df',
			'label' => 'Testimonial Type',
			'name' => 'testimonial_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'client' => 'Client',
				'partner' => 'Partner',
				'other' => 'Other',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6a23a1d7985e0',
			'label' => 'Related Case Study',
			'name' => 'related_case_study',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Please use this field if the case study is posted on this website',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'case-study',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6a420bc109f26',
			'label' => 'Related Case Study URL',
			'name' => 'related_case_study_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Please use this field only if the case study is posted on another website.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'testimonials',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a401ab3ab688',
	'title' => 'User Settings',
	'fields' => array(
		array(
			'key' => 'field_6a401ab4bead3',
			'label' => 'Linked Person',
			'name' => 'linked_person',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'people',
			),
			'post_status' => '',
			'taxonomy' => array(
				0 => 'person_role:author',
			),
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a3a318255bf0',
	'title' => 'Webinar Settings',
	'fields' => array(
		array(
			'key' => 'field_6a3a32a2ba77d',
			'label' => 'Schedule',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6a3a3182ba777',
			'label' => 'Type',
			'name' => 'webinar_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'upcoming' => 'Upcoming',
				'on-demand' => 'On-Demand',
			),
			'default_value' => 'upcoming',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6a3e1db41ee80',
			'label' => 'Series?',
			'name' => 'is_series',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Multiple webinars combined while upcoming but split up for on-demand.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_6a3a31bcba778',
			'label' => 'Start Date',
			'name' => 'webinar_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'Ymd',
			'first_day' => 1,
		),
		array(
			'key' => 'field_6a3a31f9ba77a',
			'label' => 'Start Time',
			'name' => 'webinar_time_start',
			'aria-label' => '',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'g:i a',
		),
		array(
			'key' => 'field_6a3a3249ba77c',
			'label' => 'Timezone',
			'name' => 'webinar_timezone',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'ET',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a3a31dbba779',
			'label' => 'End Date',
			'name' => 'webinar_end_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'Ymd',
			'first_day' => 1,
		),
		array(
			'key' => 'field_6a3a323bba77b',
			'label' => 'End Time',
			'name' => 'webinar_time_end',
			'aria-label' => '',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'g:i a',
		),
		array(
			'key' => 'field_6a3a32cbba77e',
			'label' => 'Registration Form',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6a3a3321ba77f',
			'label' => 'Upcoming Registration Form',
			'name' => 'form_upcoming',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'HubSpot embed code to register for the live event',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a3a3356ba780',
			'label' => 'On-Demand Registration Form',
			'name' => 'form_ondemand',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'HubSpot embed code to watch the on-demand recording',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a3ef591d13dd',
			'label' => 'Recording',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6a3ef54a65cd6',
			'label' => 'Video Embed Code',
			'name' => 'video_embed_code',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Please add a video embed code (e.g. Wistia, Vimeo, or YouTube)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a3ef55a5da4e',
			'label' => 'Recording URL',
			'name' => 'recording_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Use this field only if the recording is hosted elsewhere. The default is /recordings/{slug}.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_6a3edd28a2c1e',
			'label' => 'Other',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6a3edd7da2c1f',
			'label' => 'Presenters',
			'name' => 'presenters',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'people',
			),
			'post_status' => '',
			'taxonomy' => array(
				0 => 'person_role:presenter',
			),
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6a3eddd24103c',
			'label' => 'Hero Image',
			'name' => 'hero_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Leave empty to use the featured image in the hero block.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'webinar',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );


	acf_add_local_field_group( array(
	'key' => 'group_6a42c66719611',
	'title' => 'Stat Column Block Settings',
	'fields' => array(
		array(
			'key' => 'field_6a42c667b17bc',
			'label' => 'Stats',
			'name' => 'stats',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Each stat shows a large value with a description below. The value is shown exactly as typed — any format works ("2,000", "43%", "$1.2M", ">1 million", or a word).',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Stat',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6a42c6c8357d9',
					'label' => 'Value',
					'name' => 'stat_value',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'The headline figure, shown verbatim. e.g. 2,000 — 43% — $1.2M — >1 million',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a42c667b17bc',
				),
				array(
					'key' => 'field_6a42c6ef357da',
					'label' => 'Description',
					'name' => 'stat_description',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => '',
					'parent_repeater' => 'field_6a42c667b17bc',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'momentive/stat-columns',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );


	// -------------------------------------------------------------------------
	// Whitepaper Settings
	// -------------------------------------------------------------------------
	// hero_image field key (field_6a45de7b50be7) matches what the manually-built
	// reference posts stored in _hero_image. Keep this key stable — the migration
	// script and any existing rebuilt posts reference it.

	acf_add_local_field_group( array(
	'key' => 'group_6a45de7a50be6',
	'title' => 'Whitepaper Settings',
	'fields' => array(
		array(
			'key' => 'field_6a45de7b50be7',
			'label' => 'Hero Image',
			'name' => 'hero_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Optional page-hero override. Leave empty to use the featured image in the hero block. The featured image (_thumbnail_id) is used on archive cards regardless.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'thumbnail',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'whitepaper',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

} );


